/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { IERC20Contract } from "./IERC20";
import { LatticeStakingPoolContract } from "./LatticeStakingPool";
import { LatticeTokenContract } from "./LatticeToken";
import { MigrationsContract } from "./Migrations";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "IERC20"): IERC20Contract;
      require(name: "LatticeStakingPool"): LatticeStakingPoolContract;
      require(name: "LatticeToken"): LatticeTokenContract;
      require(name: "Migrations"): MigrationsContract;
    }
  }
}

export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  LatticeStakingPoolContract,
  LatticeStakingPoolInstance,
} from "./LatticeStakingPool";
export { LatticeTokenContract, LatticeTokenInstance } from "./LatticeToken";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
